---

- name: manage nginx package.
  package:
    name: nginx
  notify: restart nginx

- name: Configure Nginx defaults
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  
- name: Manage /etc/nginx/proxy_params file
  copy:
    src: proxy_params
    dest: /etc/nginx/proxy_params

- name: enable nginx service (start at system boot)
  service:
    name: nginx
    enabled: yes
    
- name: start nginx service if it isn't running
  service:
    name: nginx
    state: started

- name: Create /etc/nginx/options.d
  file: 
    path: /etc/nginx/options.d
    state: directory
    owner: root
    group: root
    mode: 0775
  
