- hosts: all:!alertlogic
  become: yes
  become_user: root
  vars_prompt:
    - name: vpc_name
      private: no
  vars_files:
    - ~/ansible-secrets/vars/{{ vpc_name }}.yml
    - ~/ansible-secrets/vars/common.yml
  roles:
    - certificates
