- hosts: builder

  become: yes
  become_user: root

  #vars_files:
  #  - ~/ansible-secrets/vars/jenkins-master.yml

  roles:
    - role : java
    - role : fpm
    - role : s3p
    - role : jenkins-build-host
