---

- name: install s3p for building release pipelines
  shell: pip install --upgrade git+https://github.com/russellballestrini/s3p.git


# required to extract phantomjs-1.9.8-linux-x86_64.tar.bz2
- name: Ensure bzip2 is installed.
  yum:
    name: bzip2
    state: installed
    
- name: Ensure wget is installed.
  yum:
    name: wget
    state: installed

- name: Ensure rpmdevtools is installed (for building rpm files from spec files).
  yum:
    name: rpmdevtools
    state: installed
    
- name: Install haproxy build dependencies.
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - pcre-devel
    - gcc
    - openssl-devel
    - make

- name: Ensure epel-release is installed.
  yum: 
    name: epel-release
    state: installed

- name: Ensure nodejs is installed.
  yum: 
    name: nodejs
    state: installed

- name: Ensure npm is installed.
  yum: 
    name: npm
    state: installed
