---
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar

jenkins_plugins:
  - git
  - ssh-agent
  - ssh-slaves
  - thinBackup

jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_admin_username: admin
jenkins_admin_password: admin

jenkins_init_changes:
  - {option: "JENKINS_ARGS", value: "--prefix={{ jenkins_url_prefix }}"}
  - {option: "JENKINS_JAVA_OPTIONS", value: "{{ jenkins_java_options }}"}
