---

- name: Check if JumpCloud is already installed
  shell: "[ -f /opt/jc/jcagent.conf ] && echo 'found' || echo 'not-found'"
  register: jc_installed

- name: Install JumpCloud
  shell: "curl --header 'x-connect-key: {{ jumpcloud_x_connect_key }}' https://kickstart.jumpcloud.com/Kickstart | sudo bash"
  when: jc_installed.stdout == 'not-found'
  register: jc_kickstarted

- name: ensure jcagent service is started
  service:
    name: jcagent
    state: started

- name: wait for /opt/jc/jcagent.conf to exist
  wait_for: 
    path: /opt/jc/jcagent.conf

- name: include packer
  include: packer.yml
  when: packer

- name: register and tag
  include: register-and-tag.yml
  when: not packer
