---

- name: Check if JumpCloud is already installed
  shell: "[ -f /opt/jc/jcagent.conf ] && echo 'found' || echo 'not-found'"
  register: jc_installed

#- name: Update time
#  shell: "ntpdate -u pool.ntp.org"
#  when: "not jc_installed.stdout"

- name: Install JumpCloud
  shell: "curl --header 'x-connect-key: {{ jumpcloud_x_connect_key }}' https://kickstart.jumpcloud.com/Kickstart | sudo bash"
  when: jc_installed.stdout == 'not-found'

- name: restart jcagent
  service:
    name: jcagent
    state: restarted

- name: wait for /opt/jc/jcagent.conf to exist
  wait_for: 
    path: /opt/jc/jcagent.conf

- name: Get and register the jumpcloud system key from config. 
  shell: "cat /opt/jc/jcagent.conf | python -c 'import sys, json; print json.load(sys.stdin)[sys.argv[1]]' systemKey"
  register: system_key

- name: Use jumpcloud api and curl to tag this system.
  shell: >
    curl -iq -d '{ "tags" : {{ jumpcloud_system_tags | to_json }} }' -X "PUT" -H "Content-Type: application/json" -H "Accept: application/json" -H "x-api-key: {{ jumpcloud_api_key }}" --url https://console.jumpcloud.com/api/systems/{{ system_key.stdout }}
