---
- name: Download Agent
  get_url:
    url: https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install
    dest: /tmp/aws_inspector_agent_install

- name: Install Agent
  command:  chdir=/tmp bash aws_inspector_agent_install
