---

- name: include no-selinux
  include: no-selinux.yml

- name: configure UTC time
  shell: ln -fs /usr/share/zoneinfo/UTC /etc/localtime

- name: manage /usr/local/sbin/sethostname.sh
  copy:
    src: sethostname.sh
    dest: /usr/local/sbin/sethostname.sh
    owner: root
    group: root
    mode: 0750
  register: sethostname

- name: execute /usr/local/sbin/sethostname.sh
  shell: /usr/local/sbin/sethostname.sh {{ name }}
  when: sethostname.changed

- name: install epel-release repo.
  yum:
    name: epel-release

- name: install pip
  yum:
    name: python-pip
