---

- name: include no-selinux
  include: no-selinux.yml

- name: include netcat
  include: netcat.yml

- name: configure UTC time
  shell: ln -fs /usr/share/zoneinfo/UTC /etc/localtime

- name: include hostname
  include: hostname.yml
  when: not packer

- name: install epel-release repo.
  yum:
    name: epel-release

- name: install pip
  yum:
    name: python-pip
