---

- name: manage authorized_keys files
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: present
  with_items: "{{ authorized_keys | default([]) }}"

- name: manage /etc/ssh/sshd_config 
  copy: 
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - restart sshd
